Models/Auction.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{

    public enum AuctionState
    {
        DRAFT, READY, OPEN, SOLD, EXPIRED
    }


    [Table("Auction")]
    public partial class Auction
    {
        [Key]
        public int id { get; set; }
        public string productName { get; set; }
        public double duration { get; set; }
        public double starting_price { get; set; }
        public DateTime? create_datetime { get; set; }
        public DateTime? open_datetime { get; set; }
        public DateTime? close_datetime { get; set; }
        public bool deleted { get; set; }
        public AuctionState? state { get; set; }
        public double increment { get; set; }
        public string lastBid { get; set; }
        public byte[] image { get; set; }
        [Timestamp]
        public virtual ICollection<Bid> bids { get; set; }

        [NotMapped]
        public HttpPostedFileBase imageToUpload { get; set; }
    }

    public class AuctionDetailModelView
    {
        public Auction auction { get; set; }
        public string[] bids { get; set; }

        public AuctionDetailModelView ()
        {
            this.bids = new string[10];
        }
    }
}

Controllers/AuctionsController.cs
using Microsoft.AspNet.SignalR;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Hubs;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class AuctionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        private List<string> parseSearchString(string s)
        {
            List<string> list = new List<string>();

            if (s == null)
                return list;

            const char separator = ' ';
            string [] words = s.Split(separator);

            for(int i = 0; i < words.Length; i++)
            {
                list.Add(words[i]);
            }

            return list;
        }

        // GET: Auctions
        public ActionResult Index(string name, string state, string min, string max, int? page)
        {
            List<string> list = parseSearchString(name);

            if (User.IsInRole("Admin"))
                ViewBag.Role = "Admin";
            else
            {
                if (User.Identity.Name.Equals(""))
                    ViewBag.Role = "NoAuth";
                else
                    ViewBag.Role = "User";
            }

            long minPrice = 0;
            long maxPrice = 0;

            if (!String.IsNullOrEmpty(max))
                maxPrice = long.Parse(max);

            if (!String.IsNullOrEmpty(min))
                minPrice = long.Parse(min);

            var states = new List<String>();
            states.Add("DRAFT");
            states.Add("READY");
            states.Add("OPEN");
            states.Add("SOLD");
            states.Add("EXPIRED");

            ViewBag.State = new SelectList(states);

            var auctions = from m in db.Auctions select m;

            if (!(User.IsInRole("Admin")))
            {
                auctions = auctions.Where(s => !(s.state == AuctionState.READY));
            }

            if (list.Count != 0)
            {
                foreach(string n in list)
                {
                    auctions = auctions.Where(s => s.productName.Contains(n));
                }
            }

            if (!String.IsNullOrEmpty(state))
            {
                if (state == "OPEN")
                    auctions = auctions.Where(s => s.state == AuctionState.OPEN);
                else if (state == "READY")
                    auctions = auctions.Where(s => s.state == AuctionState.READY);
                else if (state == "SOLD")
                    auctions = auctions.Where(s => s.state == AuctionState.SOLD);
                else if (state == "EXPIRED")
                    auctions = auctions.Where(s => s.state == AuctionState.EXPIRED);
                else if (state == "DRAFT")
                    auctions = auctions.Where(s => s.state == AuctionState.DRAFT);
            }

            if (!String.IsNullOrEmpty(min))
                auctions = auctions.Where(s => s.starting_price >= minPrice);
            if (!String.IsNullOrEmpty(max))
                auctions = auctions.Where(s => s.starting_price <= maxPrice);

            int pagination = 10; // when 10 it shows 9 per page
            int pagenumber = (page ?? 1);

            return View(auctions.OrderByDescending(s => s.create_datetime).ToPagedList(pagenumber, pagination));
        }

        // GET: Auctions/Details/5
        public ActionResult Details(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Auction auction = db.Auctions.Find(id);

            if(auction == null)
            {
                return HttpNotFound();
            }

            var bids = from m in db.Bids select m;
            bids = bids.Where(s => s.idAuction == id).OrderBy(k => k.create_datetime);

            List<string> bidUsersList = new List<string>();

            bidUsersList = bids.Select(u => u.idUser.ToString()).ToList();
            bidUsersList.Reverse();

            AuctionDetailModelView auctionDetailModelView = new AuctionDetailModelView();
            auctionDetailModelView.auction = auction;

            for (int i = 0; i < 10 && bidUsersList.Count > i; i++)
            {
                ApplicationUser user = db.Users.Find(bidUsersList[i]);
                auctionDetailModelView.bids[i] = user.UserName;
            }

            return View(auctionDetailModelView);
        }

        // GET: Auctions/Create
        [System.Web.Mvc.Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Auctions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,productName,duration,starting_price,create_datetime,open_datetime,close_datetime,deleted,state,increment,imageToUpload")] Auction auction)
        {
            if (ModelState.IsValid)
            {
                if (auction.imageToUpload != null)
                {
                    auction.image = new byte[auction.imageToUpload.ContentLength];
                    auction.imageToUpload.InputStream.Read(auction.image, 0, auction.image.Length);
                }
                auction.create_datetime = DateTime.Now;
                auction.lastBid = " ";
                auction.state = AuctionState.READY;
                db.Auctions.Add(auction);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(auction);
        }

        // GET: Auctions/Edit/5
        [System.Web.Mvc.Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Auction auction = db.Auctions.Find(id);
            if (auction == null)
            {
                return HttpNotFound();
            }

            if(auction.state == AuctionState.OPEN)
            {
                return RedirectToAction("Index");
            }
            return View(auction);
        }

        // POST: Auctions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,productName,duration,starting_price,create_datetime,open_datetime,close_datetime,deleted,state,increment,imageToUpload")] Auction auction)
        {
            if(ModelState.IsValid)
            {
                Auction a = db.Auctions.Find(auction.id);
                if (auction.imageToUpload != null)
                {
                    auction.image = new byte[auction.imageToUpload.ContentLength];
                    auction.imageToUpload.InputStream.Read(auction.image, 0, auction.image.Length);
                    a.image = auction.image;
                }
                a.duration = auction.duration;
                a.productName = auction.productName;
                a.starting_price = auction.starting_price;
                a.increment = auction.increment;

                db.Entry(a).CurrentValues.SetValues(db.Auctions);
                db.SaveChanges();

                return RedirectToAction("Index");

            }

            return View(auction);
        }

        // GET: Auctions/Delete/5
        [System.Web.Mvc.Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Auction auction = db.Auctions.Find(id);
            if (auction == null)
            {
                return HttpNotFound();
            }

            if(auction.state == AuctionState.OPEN)
            {
                return RedirectToAction("Index");
            }
            return View(auction);
        }

        // POST: Auctions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Auction auction = db.Auctions.Find(id);
            auction.deleted = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public void placePid(string userName, string idAuction)
        {
            var context = GlobalHost.ConnectionManager.GetHubContext<BidHub>();
            ApplicationDbContext db = new ApplicationDbContext();

            BidInfo bidInfo = new BidInfo();
            Bid bid = new Bid();

            bidInfo.idAuction = idAuction;
            bidInfo.last10Bids[0] = userName;

            long id = long.Parse(idAuction);

            Auction auction = db.Auctions.Find(id);
            bidInfo.increment = auction.increment;
            auction.starting_price += auction.increment;
            var users = from n in db.Users select n;

            users = users.Where(s => s.UserName == userName);

            ApplicationUser user = users.First();

            if (user.tokens < 1)
            {
                context.Clients.All.noMoreTokens(userName, id);
                return;
            }
            else

Views/Auctions/Create.cshtml
@model WebApplication1.Models.Auction

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Auctions", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Auction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.productName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.productName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.productName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.starting_price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.starting_price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.starting_price, "", new { @class = "text-danger" })
            </div>
        </div>





        <div class="form-group">
            @Html.LabelFor(model => model.increment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.increment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.increment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imageToUpload, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.imageToUpload, new { type = "file" })
                @Html.ValidationMessageFor(model => model.imageToUpload, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Auctions/Delete.cshtml
@model WebApplication1.Models.Auction

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Auction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.productName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.productName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.starting_price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.starting_price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.create_datetime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.create_datetime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.open_datetime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.open_datetime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.close_datetime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.close_datetime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.deleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.deleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.state)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.state)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.increment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.increment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastBid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastBid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @HtmlHelpers.showimage(Model.image)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Auctions/Details.cshtml
@model WebApplication1.Models.AuctionDetailModelView

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div class="row">


    <div class="col-md-3">
        @Html.DisplayFor(ModelItem => @Model.auction)
    </div>

    <br />
    <div class="col-md-3">

        <div class="panel panel-danger">
            <div class="panel-heading">
                <center><h3 class="panel-title">Last bids</h3></center>
            </div>
            <div class="panel-body">
                <center><p><h4><b style="visibility:hidden" id='user1-@Model.auction.id'></b></h4></p></center>
                <center><p><h4><b style="visibility:hidden" id='user2-@Model.auction.id'></b></h4></p></center>
                <center><p><h4><b style="visibility:hidden" id='user3-@Model.auction.id'></b></h4></p></center>
                <center><p><h4><b style="visibility:hidden" id='user4-@Model.auction.id'></b></h4></p></center>
                <center><p><h4><b style="visibility:hidden" id='user5-@Model.auction.id'></b></h4></p></center>
                <center><p><h4><b style="visibility:hidden" id='user6-@Model.auction.id'></b></h4></p></center>
                <center><p><h4><b style="visibility:hidden" id='user7-@Model.auction.id'></b></h4></p></center>
                <center><p><h4><b style="visibility:hidden" id='user8-@Model.auction.id'></b></h4></p></center>
                <center><p><h4><b style="visibility:hidden" id='user9-@Model.auction.id'></b></h4></p></center>
                <center><p><h4><b style="visibility:hidden" id='user10-@Model.auction.id'></b></h4></p></center>

            </div>
        </div>
    </div>


</div>
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
@section scripts
{
    @Scripts.Render("~/Scripts/jquery-1.10.2.js")
    @Scripts.Render("~/Scripts/jquery.signalR-2.2.1.js")
    @Scripts.Render("~/signalr/hubs")
    @Scripts.Render("~/Scripts/custom_scripts/custom_scripts.js")
}

<p>
    @Html.ActionLink("Back to List", "Index")
</p>
@{
    var first = Model.bids[0];
    var second = Model.bids[1];
    var third = Model.bids[2];
    var fourth = Model.bids[3];
    var fifth = Model.bids[4];
    var sixth = Model.bids[5];
    var seventh = Model.bids[6];
    var eighth = Model.bids[7];
    var ninth = Model.bids[8];
    var tenth = Model.bids[9];

}
<script>
    if ('@first' != "") {
        document.getElementById('user1-@Model.auction.id').style.visibility = 'visible';
        document.getElementById('user1-@Model.auction.id').innerHTML = '@first';
    }
    if ('@second' != "") {
        document.getElementById('user2-@Model.auction.id').style.visibility = 'visible';
        document.getElementById('user2-@Model.auction.id').innerHTML = '@second';
    }
    if ('@third' != "") {
        document.getElementById('user3-@Model.auction.id').style.visibility = 'visible';
        document.getElementById('user3-@Model.auction.id').innerHTML = '@third';
    }
    if ('@fourth' != "") {
        document.getElementById('user4-@Model.auction.id').style.visibility = 'visible';
        document.getElementById('user4-@Model.auction.id').innerHTML = '@fourth';
    }
    if ('@fifth' != "") {
        document.getElementById('user5-@Model.auction.id').style.visibility = 'visible';
        document.getElementById('user5-@Model.auction.id').innerHTML = '@fifth';
    }
    if ('@sixth' != "") {
        document.getElementById('user6-@Model.auction.id').style.visibility = 'visible';
        document.getElementById('user6-@Model.auction.id').innerHTML = '@sixth';
    }
    if ('@seventh' != "") {
        document.getElementById('user7-@Model.auction.id').style.visibility = 'visible';
        document.getElementById('user7-@Model.auction.id').innerHTML = '@seventh';
    }
    if ('@eighth' != "") {
        document.getElementById('user8-@Model.auction.id').style.visibility = 'visible';
        document.getElementById('user8-@Model.auction.id').innerHTML = '@eighth';
    }
    if ('@ninth' != "") {
        document.getElementById('user9-@Model.auction.id').style.visibility = 'visible';
        document.getElementById('user9-@Model.auction.id').innerHTML = '@ninth';
    }
    if ('@tenth' != "") {
        document.getElementById('user10-@Model.auction.id').style.visibility = 'visible';
        document.getElementById('user10-@Model.auction.id').innerHTML = '@tenth';
    }
</script>

Views/Auctions/Edit.cshtml
@model WebApplication1.Models.Auction

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Auctions", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Auction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.productName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.productName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.productName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.starting_price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.starting_price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.starting_price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.increment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.increment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.increment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imageToUpload, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.imageToUpload, new { type = "file" })
                @Html.ValidationMessageFor(model => model.imageToUpload, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Auctions/Index.cshtml
@model PagedList.IPagedList<WebApplication1.Models.Auction>
@using PagedList.Mvc;
@using WebApplication1.Helpers;

@{
    ViewBag.Title = "Index";
}
<h2> </h2>

@if (ViewBag.Role == "Admin") {
<p>
    @Html.ActionLink("Create New", "Create")
</p>
}
<div id='@User.Identity.Name' , style="visibility:hidden"> @User.Identity.Name</div>


<nav class="navbar navbar-default" style="margin-top:50px">
    <div class="container-fluid">
        <div class="collapse navbar-collapse">
            @using (Html.BeginForm("Index", "Auctions", FormMethod.Get))
            {
                var items = new List<SelectListItem>()
                {
                    new SelectListItem() { Text = "All", Value = "All" },
                    new SelectListItem() { Text = "READY", Value = "READY" },
                    new SelectListItem() { Text = "OPEN", Value = "OPEN" },
                    new SelectListItem() { Text = "SOLD", Value = "SOLD" },
                    new SelectListItem() { Text = "EXPIRED", Value = "EXPIRED" },
                };

                <div class="row">
                    <label class="col-md-1 control-label" style="text-align:right">State:</label>
                    <div class="col-md-2">
                        @Html.DropDownList("State", items, null, new { @class = "form-control" })
                    </div>
                    <label class="col-sm-1 control-label" style="text-align:right">Name:</label>
                    <div class="col-md-2">
                        @Html.TextBox("name", null, new { @class = "form-control" })
                    </div>
                    <label class="col-sm-1 control-label" style="text-align:right">Min Price:</label>
                    <div class="col-md-1">
                        @Html.TextBox("min", null, new { @class = "form-control" })
                    </div>
                    <label class="col-sm-1 control-label" style="text-align:right">Max Price:</label>
                    <div class="col-md-1">
                        @Html.TextBox("max", null, new { @class = "form-control" })
                    </div>
                    <div class="col-md-2">
                        <input class="btn btn-primary" type="submit" value="Search" />
                    </div>

                </div>
            }
        </div>
    </div>
</nav>

<div class="row">
    @foreach (var item in Model)
    {

        if (item.deleted == false)
        {
            {
                <div class="col-md-3">
                    @Html.DisplayFor(ModelItem => item)
                </div>
            }
        }
    }
</div>
<br />


Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))



<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
@section scripts
{
    @Scripts.Render("~/Scripts/jquery-1.10.2.js")
    @Scripts.Render("~/Scripts/jquery.signalR-2.2.1.js")
    @Scripts.Render("~/signalr/hubs")
    @Scripts.Render("~/Scripts/custom_scripts/custom_scripts.js")
}